[package]
name = "speak"
version = "0.1.0"
authors = ["7shi"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winrt = "0.7"
